stages:
      - check

build:
  stage: check
  image: nixos/nix

  script:
    - echo -e "\e[0Ksection_start:`date +%s`:build[collapsed=true]\r\e[0KBuilding the base..."
    - nix --extra-experimental-features nix-command --extra-experimental-features flakes build -L .
    - echo -e "\e[0Ksection_end:`date +%s`:build\r\e[0K"

    - echo -e "\e[0Ksection_start:`date +%s`:fmt\r\e[0Kcargo-fmt"
    - nix --extra-experimental-features nix-command --extra-experimental-features flakes build -L .#checks.x86_64-linux.my-crate-fmt
    - echo -e "\e[0Ksection_end:`date +%s`:fmt\r\e[0K"

    - echo -e "\e[0Ksection_start:`date +%s`:clippy\r\e[0Kcargo-clippy"
    - nix --extra-experimental-features nix-command --extra-experimental-features flakes build -L .#checks.x86_64-linux.my-crate-clippy
    - echo -e "\e[0Ksection_end:`date +%s`:clippy\r\e[0K"

    - echo -e "\e[0Ksection_start:`date +%s`:doc\r\e[0Kcargo-doc"
    - nix --extra-experimental-features nix-command --extra-experimental-features flakes build -L .#checks.x86_64-linux.my-crate-doc
    - echo -e "\e[0Ksection_end:`date +%s`:doc\r\e[0K"

    - echo -e "\e[0Ksection_start:`date +%s`:nextest\r\e[0Kcargo-nextest"
    - nix --extra-experimental-features nix-command --extra-experimental-features flakes build -L .#checks.x86_64-linux.my-crate-nextest
    - echo -e "\e[0Ksection_end:`date +%s`:nextest\r\e[0K"

    #- echo -e "\e[0Ksection_start:`date +%s`:coverage\r\e[0Kcargo-coverage"
    #- nix --extra-experimental-features nix-command --extra-experimental-features flakes build -L .#checks.x86_64-linux.my-crate-coverage
    #- echo -e "\e[0Ksection_end:`date +%s`:coverage\r\e[0K"